### ISSUE TITLE
Chapter 6 issues

### ISSUE THREAD

**Issue by clementgig** [alexandre-touret/rest-apis-versioning-workshop#54]
Missing "client_secret" variable name in command line to generate token for customer1 : 

https://github.com/alexandre-touret/rest-apis-versioning-workshop/blob/2H_WORKSHOP/docs/06-authorization.md#test-it

http --form  :8009/oauth2/token grant_type="client_credentials" client_id="customer1" **client_secret**="secret1" scope="openid book:v1:write book:v1:write number:v1:read"

**Comment by clementgig** [comment]
Possible typo in all scopes in blocks of code to copy to GatewayApplication.java :

For example :

- for authorization-server (application.properties) : with ':' separator
`authorization.clients.customer1.scopes=book:v1:read [...]`

- for GatewayApplication.java : **without** ':' separator
`hasAuthority("SCOPE_bookv1:read")`

**Comment by clementgig** [comment]
Suggestion for consistency : 

change
You can also try using inappropriate scopes (e.g., using `bookv1:read` scope for `customer2`).
to
You can also try using inappropriate scopes (e.g., using `book:v1:read` scope for `customer2`).

**Comment by alexandre-touret** [comment]
Thanks @clementgig for your feedback !
